version: '2'

services:
  mysql-server:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=analev_r
    ports:
      - "3316:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    hostname: phpmyadmin
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=toor
    depends_on:
        - mysql-server
    links:
      - mysql-server:db
    ports:
      - "8881:80"

  analev-r:
    build: .
    depends_on:
      - mysql-server
    links:
      - mysql-server:mysql-server
    ports:
      - "8880:8080"
    command: "python3 /opt/analev-r/bin/analev-r-server -D mysql+pymysql://root:toor@mysql-server/analev_r -W /opt/analev-r/r_workspace -C /opt/analev-r/gmail_credential_compose.json"
#
#  analev-r-proxy:
#    build: php_proxy
#    volumes:
#      - ./php_proxy:/var/www/html
#    depends_on:
#      - analev-r
#    links:
#      - analev-r:analev
#    ports:
#      - "8882:80"
#    command: apache2-foreground
