SET DATA_DIR=.\storage\data
SET MODULE_DIR=.\storage\module
SET WORKSPACE_DIR=.\storage\workspace

SET APP_DIR=.\app\worker
SET AUTOKILL_AFTER_ITERATION=20
SET MAX_WORKER=3

SET REDIS_HOST=10.6.2.105
SET MYSQL_HOST=10.6.2.105
SET MySQL_USER=root
SET MySQL_PASSWORD=toor
SET MYSQL_DATABASE=analev

Rscript .\app\worker\process.R